In [2]:
import pandas as pd

In [8]:
df = pd.read_csv('cost accounting.csv', sep = ',', decimal = ',')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Отметка времени   66 non-null     object
 1   Месяц             66 non-null     object
 2   Название          66 non-null     object
 3   Сумма             66 non-null     float64
 4   Категория         66 non-null     object
 5   Регулярная трата  66 non-null     bool
dtypes: bool(1), float64(1), object(4)
memory usage: 2.8+ KB

In [10]:
df.head()

,Отметка времени,Месяц,Название,Сумма,Категория,Регулярная трата
0,06.12.2022 19:04:43,Апрель,Кофе,40.0,Еда,False
1,06.12.2022 19:05:14,Март,Такси,200.0,Другое,False
2,06.12.2022 19:05:35,Июль,Супермаркет,1500.0,Еда,True
3,06.12.2022 19:06:20,Июнь,Стоматолог,3000.0,Медицина,False
4,06.12.2022 19:06:46,Май,Праздновал ДР,7405.0,Развлечения,False

Общая информация по тратам

In [11]:
df.describe()

              Сумма
count     66.000000
mean    7504.747727
std     4648.149010
min       40.000000
25%     3949.485000
50%     7525.075000
75%    11605.282500
max    17397.000000

Информация по категориям

In [14]:
df.groupby('Категория').sum().sort_values('Сумма', ascending=False)

                 Сумма  Регулярная трата
Категория
Авто         123641.48                 9
Одежда        82000.83                 0
Еда           74564.54                 7
Коммуналка    63734.15                 4
Развлечения   57283.59                 0
Другое        53920.89                 0
Медицина      40167.87                 3